### ISSUE TITLE
Invited User cannot Register

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-v2#96] opened 2015-03-16 16:54 UTC
I re-invited someone (after deleting their old invite).  They received it, clicked the accept invitation link, filled out the info, and then once he hit enter, received this error.  He tried to login but failed.

I replicated the error by sending myself an invite to a two different emails.  (One of those invitations actually didn't show up...I suppose that's it's own bug)

![unnamed](https://cloud.githubusercontent.com/assets/5350076/6671122/96717588-cbd9-11e4-8d63-955d9c802744.jpg)

**Comment by undergroundwebdesigns** [comment] 2015-03-17 03:37
I need more information than that Jamie. What do you mean you "deleted their old invite"? How did you delete the old invite, since there's no way for you to do that?

And what do you mean by "sent yourself an invite to two different emails".... thats just two invites, for two different accounts... nothing special.

I tried sending an invitation and everything worked just fine. Until I can figure out what you did, I can't fix this. Step by step, specifics, is good.

**Comment by joatu** [comment] 2015-03-17 04:14
Sorry, I deleted the user, then sent an invitation to that same email address.

I sent myself one invite to one email address and another invite to another address. One of those two never appeared.

As for signups, look at all of the people who are signed up, yet none have logged in. For some reason (that I do not know), I think people are getting the error pictured above.

**Comment by joatu** [comment] 2015-03-17 18:58
Some users are reporting being sent right to the main page when they click on the "accept invitation" button from the email.

**Comment by undergroundwebdesigns** [comment] 2015-03-19 02:36
Ok, users who are sent right to the main page, that's when they have an invalid token for some reason. Most likely cause I know of that this might happen is if they received a second invitation, and then clicked a link in the first. Eg, if you invite an email once, and then again, they will receive two emails, with two _different_ links. Only the second one is valid. The first link will send people to the home page. I've just updated the site so that if this happens, at least now there's an error message saying that the invitation token was invalid.

Unfortunately, other than that, I haven't been able to figure out what's going on here, or what would have caused your initial screenshot. The one email that wasn't working that you sent me, I see you've re-sent her invitation already (yesterday), so that emails is no good any more anyway, and I can't debug from it.

If this happens again, please do _not_ resend the invitation to that user, and _do_ tell me who it is (their email will be enough). Until then there's really not much I can do here. If I can't reproduce the bug, I can't fix it, unless I get extremely lucky, and this isn't one of those times.

**Comment by undergroundwebdesigns** [comment] 2015-03-22 22:16
Should be fixed with b53dd56bf5feda460b4cded0c604adaca807027f

**Closed by undergroundwebdesigns** 2015-03-22 22:16 UTC
Labels: bug
